run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: false
    exclude-functions:
      - fmt.Sscanf
      - fmt.Fprintf
      - fmt.Fprintln
      - (io.Closer).Close
      - (*os.File).Close
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode
      - (*encoding/json.Decoder).Decode
      - json.Unmarshal

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/ws/
      linters:
        - errcheck
    - path: internal/grpc/omnitestv1/
      linters:
        - all
