// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: omnitest/v1/agent.proto

package omnitestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent status enum.
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_IDLE        AgentStatus = 1
	AgentStatus_AGENT_STATUS_RUNNING     AgentStatus = 2
	AgentStatus_AGENT_STATUS_ERROR       AgentStatus = 3
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_IDLE",
		2: "AGENT_STATUS_RUNNING",
		3: "AGENT_STATUS_ERROR",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_IDLE":        1,
		"AGENT_STATUS_RUNNING":     2,
		"AGENT_STATUS_ERROR":       3,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_omnitest_v1_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_omnitest_v1_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{0}
}

// RegisterRequest is sent when an agent starts up.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MaxVusers     int32                  `protobuf:"varint,3,opt,name=max_vusers,json=maxVusers,proto3" json:"max_vusers,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_omnitest_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitest_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetMaxVusers() int32 {
	if x != nil {
		return x.MaxVusers
	}
	return 0
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Accepted                 bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ControllerId             string                 `protobuf:"bytes,2,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_omnitest_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitest_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

// HeartbeatRequest is sent periodically by agents.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        AgentStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=omnitest.v1.AgentStatus" json:"status,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	ActiveVusers  int32                  `protobuf:"varint,5,opt,name=active_vusers,json=activeVusers,proto3" json:"active_vusers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_omnitest_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitest_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *HeartbeatRequest) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveVusers() int32 {
	if x != nil {
		return x.ActiveVusers
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_omnitest_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitest_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// StartTestRequest instructs an agent to run a test.
type StartTestRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TestRunId      string                 `protobuf:"bytes,1,opt,name=test_run_id,json=testRunId,proto3" json:"test_run_id,omitempty"`
	ScenarioYaml   string                 `protobuf:"bytes,2,opt,name=scenario_yaml,json=scenarioYaml,proto3" json:"scenario_yaml,omitempty"`
	AssignedVusers int32                  `protobuf:"varint,3,opt,name=assigned_vusers,json=assignedVusers,proto3" json:"assigned_vusers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartTestRequest) Reset() {
	*x = StartTestRequest{}
	mi := &file_omnitest_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestRequest) ProtoMessage() {}

func (x *StartTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitest_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestRequest.ProtoReflect.Descriptor instead.
func (*StartTestRequest) Descriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StartTestRequest) GetTestRunId() string {
	if x != nil {
		return x.TestRunId
	}
	return ""
}

func (x *StartTestRequest) GetScenarioYaml() string {
	if x != nil {
		return x.ScenarioYaml
	}
	return ""
}

func (x *StartTestRequest) GetAssignedVusers() int32 {
	if x != nil {
		return x.AssignedVusers
	}
	return 0
}

type StartTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTestResponse) Reset() {
	*x = StartTestResponse{}
	mi := &file_omnitest_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestResponse) ProtoMessage() {}

func (x *StartTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitest_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestResponse.ProtoReflect.Descriptor instead.
func (*StartTestResponse) Descriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StartTestResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StartTestResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// StopTestRequest instructs an agent to stop a running test.
type StopTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestRunId     string                 `protobuf:"bytes,1,opt,name=test_run_id,json=testRunId,proto3" json:"test_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTestRequest) Reset() {
	*x = StopTestRequest{}
	mi := &file_omnitest_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestRequest) ProtoMessage() {}

func (x *StopTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitest_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestRequest.ProtoReflect.Descriptor instead.
func (*StopTestRequest) Descriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StopTestRequest) GetTestRunId() string {
	if x != nil {
		return x.TestRunId
	}
	return ""
}

type StopTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTestResponse) Reset() {
	*x = StopTestResponse{}
	mi := &file_omnitest_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestResponse) ProtoMessage() {}

func (x *StopTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitest_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestResponse.ProtoReflect.Descriptor instead.
func (*StopTestResponse) Descriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StopTestResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

// MetricReport is streamed from agent to controller during test execution.
type MetricReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TestRunId     string                 `protobuf:"bytes,2,opt,name=test_run_id,json=testRunId,proto3" json:"test_run_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalRequests int64                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalErrors   int64                  `protobuf:"varint,5,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	Rps           float64                `protobuf:"fixed64,6,opt,name=rps,proto3" json:"rps,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,7,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P50LatencyMs  float64                `protobuf:"fixed64,8,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P95LatencyMs  float64                `protobuf:"fixed64,9,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs  float64                `protobuf:"fixed64,10,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	ActiveVusers  int32                  `protobuf:"varint,11,opt,name=active_vusers,json=activeVusers,proto3" json:"active_vusers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricReport) Reset() {
	*x = MetricReport{}
	mi := &file_omnitest_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricReport) ProtoMessage() {}

func (x *MetricReport) ProtoReflect() protoreflect.Message {
	mi := &file_omnitest_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricReport.ProtoReflect.Descriptor instead.
func (*MetricReport) Descriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *MetricReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricReport) GetTestRunId() string {
	if x != nil {
		return x.TestRunId
	}
	return ""
}

func (x *MetricReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricReport) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *MetricReport) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

func (x *MetricReport) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *MetricReport) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *MetricReport) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *MetricReport) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *MetricReport) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *MetricReport) GetActiveVusers() int32 {
	if x != nil {
		return x.ActiveVusers
	}
	return 0
}

type StreamMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsResponse) Reset() {
	*x = StreamMetricsResponse{}
	mi := &file_omnitest_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsResponse) ProtoMessage() {}

func (x *StreamMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitest_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsResponse.ProtoReflect.Descriptor instead.
func (*StreamMetricsResponse) Descriptor() ([]byte, []int) {
	return file_omnitest_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StreamMetricsResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_omnitest_v1_agent_proto protoreflect.FileDescriptor

const file_omnitest_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x17omnitest/v1/agent.proto\x12\vomnitest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"max_vusers\x18\x03 \x01(\x05R\tmaxVusers\x12@\n" +
	"\x06labels\x18\x04 \x03(\v2(.omnitest.v1.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rcontroller_id\x18\x02 \x01(\tR\fcontrollerId\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\"\xc4\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.omnitest.v1.AgentStatusR\x06status\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x01R\vmemoryUsage\x12#\n" +
	"\ractive_vusers\x18\x05 \x01(\x05R\factiveVusers\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\x80\x01\n" +
	"\x10StartTestRequest\x12\x1e\n" +
	"\vtest_run_id\x18\x01 \x01(\tR\ttestRunId\x12#\n" +
	"\rscenario_yaml\x18\x02 \x01(\tR\fscenarioYaml\x12'\n" +
	"\x0fassigned_vusers\x18\x03 \x01(\x05R\x0eassignedVusers\"T\n" +
	"\x11StartTestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"1\n" +
	"\x0fStopTestRequest\x12\x1e\n" +
	"\vtest_run_id\x18\x01 \x01(\tR\ttestRunId\",\n" +
	"\x10StopTestResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\"\x9c\x03\n" +
	"\fMetricReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1e\n" +
	"\vtest_run_id\x18\x02 \x01(\tR\ttestRunId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x03R\rtotalRequests\x12!\n" +
	"\ftotal_errors\x18\x05 \x01(\x03R\vtotalErrors\x12\x10\n" +
	"\x03rps\x18\x06 \x01(\x01R\x03rps\x12$\n" +
	"\x0eavg_latency_ms\x18\a \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep50_latency_ms\x18\b \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\t \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\n" +
	" \x01(\x01R\fp99LatencyMs\x12#\n" +
	"\ractive_vusers\x18\v \x01(\x05R\factiveVusers\";\n" +
	"\x15StreamMetricsResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged*t\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AGENT_STATUS_IDLE\x10\x01\x12\x18\n" +
	"\x14AGENT_STATUS_RUNNING\x10\x02\x12\x16\n" +
	"\x12AGENT_STATUS_ERROR\x10\x032\x8a\x03\n" +
	"\fAgentService\x12G\n" +
	"\bRegister\x12\x1c.omnitest.v1.RegisterRequest\x1a\x1d.omnitest.v1.RegisterResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.omnitest.v1.HeartbeatRequest\x1a\x1e.omnitest.v1.HeartbeatResponse\x12J\n" +
	"\tStartTest\x12\x1d.omnitest.v1.StartTestRequest\x1a\x1e.omnitest.v1.StartTestResponse\x12G\n" +
	"\bStopTest\x12\x1c.omnitest.v1.StopTestRequest\x1a\x1d.omnitest.v1.StopTestResponse\x12P\n" +
	"\rStreamMetrics\x12\x19.omnitest.v1.MetricReport\x1a\".omnitest.v1.StreamMetricsResponse(\x01B7Z5github.com/omnitest/omnitest/internal/grpc/omnitestv1b\x06proto3"

var (
	file_omnitest_v1_agent_proto_rawDescOnce sync.Once
	file_omnitest_v1_agent_proto_rawDescData []byte
)

func file_omnitest_v1_agent_proto_rawDescGZIP() []byte {
	file_omnitest_v1_agent_proto_rawDescOnce.Do(func() {
		file_omnitest_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omnitest_v1_agent_proto_rawDesc), len(file_omnitest_v1_agent_proto_rawDesc)))
	})
	return file_omnitest_v1_agent_proto_rawDescData
}

var file_omnitest_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_omnitest_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_omnitest_v1_agent_proto_goTypes = []any{
	(AgentStatus)(0),              // 0: omnitest.v1.AgentStatus
	(*RegisterRequest)(nil),       // 1: omnitest.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 2: omnitest.v1.RegisterResponse
	(*HeartbeatRequest)(nil),      // 3: omnitest.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 4: omnitest.v1.HeartbeatResponse
	(*StartTestRequest)(nil),      // 5: omnitest.v1.StartTestRequest
	(*StartTestResponse)(nil),     // 6: omnitest.v1.StartTestResponse
	(*StopTestRequest)(nil),       // 7: omnitest.v1.StopTestRequest
	(*StopTestResponse)(nil),      // 8: omnitest.v1.StopTestResponse
	(*MetricReport)(nil),          // 9: omnitest.v1.MetricReport
	(*StreamMetricsResponse)(nil), // 10: omnitest.v1.StreamMetricsResponse
	nil,                           // 11: omnitest.v1.RegisterRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_omnitest_v1_agent_proto_depIdxs = []int32{
	11, // 0: omnitest.v1.RegisterRequest.labels:type_name -> omnitest.v1.RegisterRequest.LabelsEntry
	0,  // 1: omnitest.v1.HeartbeatRequest.status:type_name -> omnitest.v1.AgentStatus
	12, // 2: omnitest.v1.MetricReport.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 3: omnitest.v1.AgentService.Register:input_type -> omnitest.v1.RegisterRequest
	3,  // 4: omnitest.v1.AgentService.Heartbeat:input_type -> omnitest.v1.HeartbeatRequest
	5,  // 5: omnitest.v1.AgentService.StartTest:input_type -> omnitest.v1.StartTestRequest
	7,  // 6: omnitest.v1.AgentService.StopTest:input_type -> omnitest.v1.StopTestRequest
	9,  // 7: omnitest.v1.AgentService.StreamMetrics:input_type -> omnitest.v1.MetricReport
	2,  // 8: omnitest.v1.AgentService.Register:output_type -> omnitest.v1.RegisterResponse
	4,  // 9: omnitest.v1.AgentService.Heartbeat:output_type -> omnitest.v1.HeartbeatResponse
	6,  // 10: omnitest.v1.AgentService.StartTest:output_type -> omnitest.v1.StartTestResponse
	8,  // 11: omnitest.v1.AgentService.StopTest:output_type -> omnitest.v1.StopTestResponse
	10, // 12: omnitest.v1.AgentService.StreamMetrics:output_type -> omnitest.v1.StreamMetricsResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_omnitest_v1_agent_proto_init() }
func file_omnitest_v1_agent_proto_init() {
	if File_omnitest_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omnitest_v1_agent_proto_rawDesc), len(file_omnitest_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_omnitest_v1_agent_proto_goTypes,
		DependencyIndexes: file_omnitest_v1_agent_proto_depIdxs,
		EnumInfos:         file_omnitest_v1_agent_proto_enumTypes,
		MessageInfos:      file_omnitest_v1_agent_proto_msgTypes,
	}.Build()
	File_omnitest_v1_agent_proto = out.File
	file_omnitest_v1_agent_proto_goTypes = nil
	file_omnitest_v1_agent_proto_depIdxs = nil
}
